import {
  signInAction,
  signUpAction,
  forgotPasswordAction,
  resetPasswordAction,
} from "./auth";

import {
  createGoalAction,
  updateGoalAction,
  deleteGoalAction,
  getGoalsAction,
  getGoalTitleAction,
  createTransactionAction,
  createTransactionFormAction,
  getGoalByIdAction,
  getGoalTransactionsAction,
  getRecentAchievementsAction,
  markGoalAsCompletedAction,
  getMonthlySummaryAction,
  getReportsSummaryAction,
  getMonthlyAnalysisAction,
  getCategoryReportsAction,
  getGoalProgressReportsAction,
  getAllTransactionsAction,
  getDailyTipAction,
  getFinancialTipsAction,
  getTipDetailsAction,
  generateGoalFromPromptAction,
  getGoalGenerationLimitAction,
} from "./goals";

export const actions = {
  auth: {
    signIn: signInAction,
    signUp: signUpAction,
    forgotPassword: forgotPasswordAction,
    resetPassword: resetPasswordAction,
  },
  goals: {
    create: createGoalAction,
    update: updateGoalAction,
    delete: deleteGoalAction,
    get: getGoalsAction,
    getTitle: getGoalTitleAction,
    getById: getGoalByIdAction,
    getTransactions: getGoalTransactionsAction,
    createTransaction: createTransactionAction,
    createTransactionForm: createTransactionFormAction,
    getRecentAchievements: getRecentAchievementsAction,
    markAsCompleted: markGoalAsCompletedAction,
    getMonthlySummary: getMonthlySummaryAction,
    getReportsSummary: getReportsSummaryAction,
    getMonthlyAnalysis: getMonthlyAnalysisAction,
    getCategoryReports: getCategoryReportsAction,
    getGoalProgressReports: getGoalProgressReportsAction,
    getAllTransactions: getAllTransactionsAction,
    getDailyTip: getDailyTipAction,
    getFinancialTips: getFinancialTipsAction,
    getTipDetails: getTipDetailsAction,
    generateGoalFromPrompt: generateGoalFromPromptAction,
    getGoalGenerationLimit: getGoalGenerationLimitAction,
  },
};
